### ISSUE TITLE
discussion: suppose `emit SetCurve` inSharesFactory constructor

### ISSUE THREAD

**Issue by aquariuslt** [value4value/time4value#33]
## discussion

https://github.com/value4value/time4value/blob/82264548af17113099e215d71833444251ff326c/contracts/core/SharesFactoryV1.sol#L64-L71

should add `emit SetCurve(0);`

**Comment by 0xashu** [comment]
Maybe we can call `setCurveType` in the `constructor()`, and that emits the event.

**Comment by 0xashu** [comment]
@aquariuslt 
I think it doesn't make sense to call `setCurveType` in the constructor, since it needs to be declared in advance, and secondly it needs to repeat `setCurveType` code in the constructor, so based on these points, I suggest closing this issue.
